# [package]
# name = "pi_bevy_plugin"
# version = "0.1.0"
# authors = ["moyy <myy412001799@gmail.com>"]
# edition = "2021"
# description = "Renderer for PI Engine"
# repository = "https://github.com/GaiaWorld/pi_render_bevy"
# license = "MIT OR Apache-2.0"
# keywords = ["pi", "bevy"]

[workspace]
members = ["crates/*"]
resolver = "2"

[patch."https://github.com/GaiaWorld/pi_post_process"]
pi_postprocess = { path = "../pi_post_process"}

# [patch."https://github.com/GaiaWorld/pi_render"]
# pi_render = { path = "../pi_render" }

# [patch."https://github.com/GaiaWorld/pi_hal"]
# pi_hal = { path = "../pi_hal" }

# [patch.crates-io]
# pi_async_graph = { path = "../pi_async_graph" }
# pi_graph = { path = "../pi_graph" }
# pi_map = { path = "../pi_map" }
